/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AgentApi,
  CallApi,
  PhoneNumberApi,
  RetellApi,
  RetellLLMApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { RetellAiCustom } from "./client-custom";

export class RetellAi extends RetellAiCustom {
  readonly agent: AgentApi;
  readonly call: CallApi;
  readonly phoneNumber: PhoneNumberApi;
  readonly retell: RetellApi;
  readonly retellLLM: RetellLLMApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.agent = new AgentApi(configuration);
    this.call = new CallApi(configuration);
    this.phoneNumber = new PhoneNumberApi(configuration);
    this.retell = new RetellApi(configuration);
    this.retellLLM = new RetellLLMApi(configuration);
  }

}
