/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BookAppointmentCalTool
 */
export interface BookAppointmentCalTool {
    /**
     * Describes when to book the appointment.
     * @type {string}
     * @memberof BookAppointmentCalTool
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookAppointmentCalTool
     */
    'type': BookAppointmentCalToolTypeEnum;
    /**
     * Name of the tool. Must be unique within all tools available to LLM at any given time (general tools + state tools + state transitions).
     * @type {string}
     * @memberof BookAppointmentCalTool
     */
    'name': string;
    /**
     * Cal.com Api key that have access to the cal.com event you want to book appointment.
     * @type {string}
     * @memberof BookAppointmentCalTool
     */
    'cal_api_key': string;
    /**
     * Cal.com event type id number for the cal.com event you want to book appointment.
     * @type {number}
     * @memberof BookAppointmentCalTool
     */
    'event_type_id': number;
    /**
     * Timezone to be used when booking appointment, must be in [IANA timezone database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If not specified, will check if user specified timezone in call, and if not, will use the timezone of the Retell servers.
     * @type {string}
     * @memberof BookAppointmentCalTool
     */
    'timezone'?: string;
}

type BookAppointmentCalToolTypeEnum = 'book_appointment_cal'


