/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CallEstablishConnectionResponse
 */
export interface CallEstablishConnectionResponse {
    /**
     * 
     * @type {string}
     * @memberof CallEstablishConnectionResponse
     */
    'error_message'?: string;
}

