/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CallDetailAllOfE2eLatency } from './call-detail-all-of-e2e-latency';
import { Utterance } from './utterance';

/**
 * 
 * @export
 * @interface CallDetailAllOf
 */
export interface CallDetailAllOf {
    /**
     * End timestamp (milliseconds since epoch) of the call. Available after call ends.
     * @type {number}
     * @memberof CallDetailAllOf
     */
    'end_timestamp'?: number;
    /**
     * Transcription of the call. Available after call ends.
     * @type {string}
     * @memberof CallDetailAllOf
     */
    'transcript'?: string;
    /**
     * Transcript of the call in the format of a list of utterance, with timestamp. Available after call ends.
     * @type {Array<Utterance>}
     * @memberof CallDetailAllOf
     */
    'transcript_object'?: Array<Utterance>;
    /**
     * Recording of the call. Available after call ends.
     * @type {string}
     * @memberof CallDetailAllOf
     */
    'recording_url'?: string;
    /**
     * Public log of the call, containing details about all the requests and responses received in LLM WebSocket, latency tracking for each turntaking, helpful for debugging and tracing. Available after call ends.
     * @type {string}
     * @memberof CallDetailAllOf
     */
    'public_log_url'?: string;
    /**
     * 
     * @type {CallDetailAllOfE2eLatency}
     * @memberof CallDetailAllOf
     */
    'e2e_latency'?: CallDetailAllOfE2eLatency;
}

