/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CallGetDetailsFilterCriteriaParameter
 */
export interface CallGetDetailsFilterCriteriaParameter {
    /**
     * Only retrieve calls that are made with specific agent(s).
     * @type {Array<string>}
     * @memberof CallGetDetailsFilterCriteriaParameter
     */
    'agent_id'?: Array<string>;
    /**
     * Exclusive. Filter calls that start before this timestamp.
     * @type {number}
     * @memberof CallGetDetailsFilterCriteriaParameter
     */
    'before_start_timestamp'?: number;
    /**
     * Inclusive. Filter calls that start on or after this timestamp.
     * @type {number}
     * @memberof CallGetDetailsFilterCriteriaParameter
     */
    'after_start_timestamp'?: number;
    /**
     * Exclusive. Filter calls that end before this timestamp.
     * @type {number}
     * @memberof CallGetDetailsFilterCriteriaParameter
     */
    'before_end_timestamp'?: number;
    /**
     * Inclusive. Filter calls that end on or after this timestamp.
     * @type {number}
     * @memberof CallGetDetailsFilterCriteriaParameter
     */
    'after_end_timestamp'?: number;
}

