/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ToolParameter } from './tool-parameter';

/**
 * 
 * @export
 * @interface CustomTool
 */
export interface CustomTool {
    /**
     * Describes what this tool does and when to call this tool.
     * @type {string}
     * @memberof CustomTool
     */
    'description': string;
    /**
     * 
     * @type {ToolParameter}
     * @memberof CustomTool
     */
    'parameters'?: ToolParameter;
    /**
     * 
     * @type {string}
     * @memberof CustomTool
     */
    'type': CustomToolTypeEnum;
    /**
     * Name of the tool. Must be unique within all tools available to LLM at any given time (general tools + state tools + state edges).
     * @type {string}
     * @memberof CustomTool
     */
    'name': string;
    /**
     * The URL we will post the function name and arguments to get a result for the function. Usually this is your server.
     * @type {string}
     * @memberof CustomTool
     */
    'url': string;
    /**
     * Determines whether the agent would say sentence like \"One moment, let me check that.\" when executing the function. Recommend to turn on if your function call takes over 1s (including network) to complete, so that your agent remains responsive.
     * @type {boolean}
     * @memberof CustomTool
     */
    'speak_during_execution': boolean;
    /**
     * Determines whether the agent would call LLM another time and speak when the result of function is obtained. Usually this needs to get turned on so user can get update for the function call.
     * @type {boolean}
     * @memberof CustomTool
     */
    'speak_after_execution': boolean;
    /**
     * The description for the sentence agent say during execution. Only applicable when speak_during_execution is true. Can write what to say or even provide examples. The default is \"The message you will say to callee when calling this tool. Make sure it fits into the conversation smoothly.\".
     * @type {string}
     * @memberof CustomTool
     */
    'execution_message_description'?: string;
}

type CustomToolTypeEnum = 'custom'


