/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EndCallTool
 */
export interface EndCallTool {
    /**
     * Describes when to end the call.
     * @type {string}
     * @memberof EndCallTool
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof EndCallTool
     */
    'type': EndCallToolTypeEnum;
    /**
     * Name of the tool. Must be unique within all tools available to LLM at any given time (general tools + state tools + state transitions).
     * @type {string}
     * @memberof EndCallTool
     */
    'name': string;
}

type EndCallToolTypeEnum = 'end_call'


