/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PhoneNumberPurchaseNumberAndBindAgentRequest
 */
export interface PhoneNumberPurchaseNumberAndBindAgentRequest {
    /**
     * Unique id of agent to bind to newly obtained number. The number will automatically use the agent when doing inbound / outbound calls.
     * @type {string}
     * @memberof PhoneNumberPurchaseNumberAndBindAgentRequest
     */
    'agent_id': string;
    /**
     * Area code of the number to obtain. Format is a 3 digit integer. Currently only supports US area code.
     * @type {number}
     * @memberof PhoneNumberPurchaseNumberAndBindAgentRequest
     */
    'area_code'?: number;
}

