/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PhoneNumberResponse
 */
export interface PhoneNumberResponse {
    /**
     * BCP 47 format of the number (+country code, then number with no space, no special characters), used as the unique identifier for phone number APIs.
     * @type {string}
     * @memberof PhoneNumberResponse
     */
    'phone_number': string;
    /**
     * Pretty printed phone number, provided for your reference.
     * @type {string}
     * @memberof PhoneNumberResponse
     */
    'phone_number_pretty': string;
    /**
     * Unique id of agent to bind to newly obtained number. The number will automatically use the agent when doing inbound / outbound calls.
     * @type {string}
     * @memberof PhoneNumberResponse
     */
    'agent_id': string;
    /**
     * Area code of the number to obtain. Format is a 3 digit integer. Currently only supports US area code.
     * @type {number}
     * @memberof PhoneNumberResponse
     */
    'area_code': number;
    /**
     * Last modification timestamp (milliseconds since epoch). Either the time of last update or creation if no updates available.
     * @type {number}
     * @memberof PhoneNumberResponse
     */
    'last_modification_timestamp': number;
}

