/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RetellLLMBase } from './retell-llmbase';
import { RetellLLMResponseAllOf } from './retell-llmresponse-all-of';
import { RetellLLMResponseAllOf1 } from './retell-llmresponse-all-of1';
import { State } from './state';
import { Tool } from './tool';

/**
 * @type RetellLLMResponse
 * @export
 */
export type RetellLLMResponse = RetellLLMBase & RetellLLMResponseAllOf & RetellLLMResponseAllOf1;


