/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { State } from './state';
import { Tool } from './tool';

/**
 * 
 * @export
 * @interface RetellLLMBase
 */
export interface RetellLLMBase {
    /**
     * General prompt that\'s appended to system prompt no matter what state the agent is in.   - System prompt (with state) = general prompt + state prompt.  - System prompt (no state) = general prompt.
     * @type {string}
     * @memberof RetellLLMBase
     */
    'general_prompt'?: string;
    /**
     * A list of tools the model may call (to get external knowledge, call API, etc). You can select from some common predefined tools like end call, transfer call, etc; or you can create your own custom tool (last option) for the LLM to use.   - Tools of LLM (with state) = general tools + state tools + state transitions  - Tools of LLM (no state) = general tools
     * @type {Array<Tool>}
     * @memberof RetellLLMBase
     */
    'general_tools'?: Array<Tool>;
    /**
     * States of the LLM. This is to help reduce prompt length and tool choices when the call can be broken into distinct states. With shorter prompts and less tools, the LLM can better focus and follow the rules, minimizing hallucination. If this field is not set, the agent would only have general prompt and general tools (essentially one state).
     * @type {Array<State>}
     * @memberof RetellLLMBase
     */
    'states'?: Array<State>;
    /**
     * Name of the starting state. Required if states is not empty.
     * @type {string}
     * @memberof RetellLLMBase
     */
    'starting_state'?: string;
    /**
     * First utterance said by the agent in the call. If not set, LLM will dynamically generate a message. If set to \"\", agent will wait for user to speak first.
     * @type {string}
     * @memberof RetellLLMBase
     */
    'begin_message'?: string;
}

