/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BookAppointmentCalTool } from './book-appointment-cal-tool';
import { CheckAvailabilityCalTool } from './check-availability-cal-tool';
import { CustomTool } from './custom-tool';
import { EndCallTool } from './end-call-tool';
import { ToolParameter } from './tool-parameter';
import { TransferCallTool } from './transfer-call-tool';

/**
 * @type Tool
 * @export
 */
export type Tool = BookAppointmentCalTool | CheckAvailabilityCalTool | CustomTool | EndCallTool | TransferCallTool;


