/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The parameters the functions accepts, described as a JSON Schema object. See [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format. Omitting parameters defines a function with an empty parameter list.
 * @export
 * @interface ToolParameter
 */
export interface ToolParameter {
    /**
     * Type must be \"object\" for a JSON Schema object.
     * @type {string}
     * @memberof ToolParameter
     */
    'type': ToolParameterTypeEnum;
    /**
     * The value of properties is an object, where each key is the name of a property and each value is a schema used to validate that property.
     * @type {{ [key: string]: any; }}
     * @memberof ToolParameter
     */
    'properties': { [key: string]: any; };
    /**
     * List of names of required property when generating this parameter. LLM will do its best to generate the required properties in its function arguments. Property must exist in properties.
     * @type {Array<string>}
     * @memberof ToolParameter
     */
    'required'?: Array<string>;
}

type ToolParameterTypeEnum = 'object'


