/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UtteranceWordsInner } from './utterance-words-inner';

/**
 * 
 * @export
 * @interface Utterance
 */
export interface Utterance {
    /**
     * Documents whether this utterance is spoken by agent or user.
     * @type {string}
     * @memberof Utterance
     */
    'role': UtteranceRoleEnum;
    /**
     * Transcript of the utterances.
     * @type {string}
     * @memberof Utterance
     */
    'content': string;
    /**
     * Array of words in the utternace with the word timestamp. Useful for understanding what word was spoken at what time. Note that the word timestamp is not guranteed to be accurate, it\'s more like an approximation.
     * @type {Array<UtteranceWordsInner>}
     * @memberof Utterance
     */
    'words': Array<UtteranceWordsInner>;
}

type UtteranceRoleEnum = 'agent' | 'user'


