/*
Retell SDK

API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

The version of the OpenAPI document: 1.0.0
Contact: founders@retellai.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UtteranceWordsInner
 */
export interface UtteranceWordsInner {
    /**
     * Word transcript (with punctuation if applicable).
     * @type {string}
     * @memberof UtteranceWordsInner
     */
    'word'?: string;
    /**
     * Start time of the word in the call in second. This is relative audio time, not wall time.
     * @type {number}
     * @memberof UtteranceWordsInner
     */
    'start'?: number;
    /**
     * End time of the word in the call in second. This is relative audio time, not wall time.
     * @type {number}
     * @memberof UtteranceWordsInner
     */
    'end'?: number;
}

